apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapps
  namespace: acr21
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapps
  template:
    metadata:
      labels:
        app: myapps
    spec:
      containers:
        - name: myapps
          image: cont21.azurecr.io/sai-image:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: cont21
