apiVersion: apps/v1
kind: Deployment
metadata:
  name: sai-image-deployment
  namespace: acr-kube
  labels:
    app: sai-image-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sai-image-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: sai-image-deployment
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: envi
                    operator: In
                    values:
                      - prob
      containers:
        - name: sai-image-deployment
          image: saikrishna998/docker-app:latest
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /_status/healthz
              port: 5000
            initialDelaySeconds: 8
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: sai-image-deployment
                  key: DB_HOST