apiVersion: apps/v1
kind: Deployment
metadata:
  name: sai-image-deployment
  namespace: acr-kube
  labels:
    app: sai-image
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sai-image
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: sai-image
    spec:
      initContainers:
      - name: init-setup
        image: busybox:latest
        command: ['sh', '-c', 'ls; pwd; sleep 10']
        envFrom:
        - configMapRef:
            name: sai-image-deployment
      containers:
      - name: sai-image
        image: saikrishna998/docker-app:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000   # Corrected port to match the containerPort
          initialDelaySeconds: 8
          periodSeconds: 10
          failureThreshold: 3  # Corrected field name
          successThreshold: 1  # Corrected field name
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000   # Corrected port to match the containerPort
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: sai-image-deployment
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: sai-image-deployment
