apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp21
  namespace: kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp21
  template:
    metadata:
      labels:
        app: myapp21
    spec:
      containers:
        - name: myapp21
          image: acr2121.azurecr.io/sai-image:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: cont21
