apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sai-image
  namespace: acr-kube
subjects:
- kind: ServiceAccount
  name: sai-image
  namespace: acr-kube
roleRef:
  kind: Role
  name: my-role
  apiGroup: rbac.authorization.k8s.io