# role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sai-image
  namespace: acr-kube
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]