apiVersion: v1
kind: Service
metadata:
  name: sai-image-app
  namespace: acr-kube
spec:
  selector:
    app: sai-image-app
  type : LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
